const oldTrafficSignMapping: {
  [oldCode: string]: {
    hasSubCode: boolean;
    code: {
      [defaultORsubcode: string]: string;
    };
  };
} = {
  '10': { hasSubCode: false, code: { default: 'F27.1' } },
  '11': { hasSubCode: false, code: { default: 'F27.1' } },
  '111': { hasSubCode: false, code: { default: 'A1.1' } },
  '112': { hasSubCode: false, code: { default: 'A1.2' } },
  '113': { hasSubCode: false, code: { default: 'A2.1' } },
  '114': { hasSubCode: false, code: { default: 'A2.2' } },
  '115': { hasSubCode: false, code: { default: 'A3.2' } },
  '116': { hasSubCode: false, code: { default: 'A3.1' } },
  '121': { hasSubCode: false, code: { default: 'A4' } },
  '122': { hasSubCode: false, code: { default: 'A5' } },
  '131': { hasSubCode: false, code: { default: 'A6' } },
  '132': { hasSubCode: false, code: { default: 'A7' } },
  '133': { hasSubCode: false, code: { default: 'A8' } },
  '141': { hasSubCode: true, code: { default: 'A9', a: 'A10' } },
  '142': { hasSubCode: false, code: { default: 'A11' } },
  '143': { hasSubCode: false, code: { default: 'A12' } },
  '144': { hasSubCode: false, code: { default: 'A13' } },
  '147': { hasSubCode: false, code: { default: 'A14' } },
  '151': { hasSubCode: false, code: { default: 'A15' } },
  '152': { hasSubCode: false, code: { default: 'A17' } },
  '153': { hasSubCode: false, code: { default: 'A18' } },
  '154': { hasSubCode: false, code: { default: 'A19' } },
  '155': { hasSubCode: false, code: { default: 'A20.1' } },
  '156': { hasSubCode: false, code: { default: 'A20.2' } },
  '161': { hasSubCode: false, code: { default: 'A21' } },
  '162': { hasSubCode: false, code: { default: 'A22.1' } },
  '163': { hasSubCode: false, code: { default: 'A22.3' } },
  '164': { hasSubCode: false, code: { default: 'A22.4' } },
  '165': { hasSubCode: false, code: { default: 'A23' } },
  '166': { hasSubCode: false, code: { default: 'A24' } },
  '167': { hasSubCode: false, code: { default: 'A25' } },
  '171': { hasSubCode: false, code: { default: 'A26' } },
  '172': { hasSubCode: false, code: { default: 'A27' } },
  '173': { hasSubCode: false, code: { default: 'A28.1' } },
  '174': { hasSubCode: false, code: { default: 'A28.2' } },
  '175': { hasSubCode: false, code: { default: 'A28.3' } },
  '176': { hasSubCode: false, code: { default: 'A29.1' } },
  '177': { hasSubCode: false, code: { default: 'A29.2' } },
  '181': { hasSubCode: false, code: { default: 'A30' } },
  '182': { hasSubCode: false, code: { default: 'A31' } },
  '183': { hasSubCode: false, code: { default: 'A32' } },
  '189': { hasSubCode: false, code: { default: 'A33' } },
  '211': { hasSubCode: false, code: { default: 'B1' } },
  '212': { hasSubCode: false, code: { default: 'B2' } },
  '221': { hasSubCode: false, code: { default: 'B3' } },
  '222': { hasSubCode: false, code: { default: 'B4' } },
  '231': { hasSubCode: false, code: { default: 'B5' } },
  '232': { hasSubCode: false, code: { default: 'B6' } },
  '311': { hasSubCode: false, code: { default: 'C1' } },
  '312': { hasSubCode: false, code: { default: 'C2' } },
  '313': { hasSubCode: false, code: { default: 'C3' } },
  '314': { hasSubCode: false, code: { default: 'C4' } },
  '315': { hasSubCode: false, code: { default: 'C5' } },
  '316': { hasSubCode: false, code: { default: 'C6' } },
  '317': { hasSubCode: false, code: { default: 'C7' } },
  '318': { hasSubCode: false, code: { default: 'C8' } },
  '319': { hasSubCode: false, code: { default: 'C9' } },
  '321': { hasSubCode: false, code: { default: 'C10' } },
  '322': { hasSubCode: false, code: { default: 'C12' } },
  '323': { hasSubCode: false, code: { default: 'C13' } },
  '324': { hasSubCode: false, code: { default: 'C15' } },
  '325': { hasSubCode: false, code: { default: 'C16' } },
  '331': { hasSubCode: false, code: { default: 'C17' } },
  '332': { hasSubCode: false, code: { default: 'C18' } },
  '333': { hasSubCode: false, code: { default: 'C19' } },
  '334': { hasSubCode: false, code: { default: 'C20' } },
  '341': { hasSubCode: false, code: { default: 'C21' } },
  '342': { hasSubCode: false, code: { default: 'C22' } },
  '343': { hasSubCode: false, code: { default: 'C23' } },
  '344': { hasSubCode: false, code: { default: 'C24' } },
  '345': { hasSubCode: false, code: { default: 'C25' } },
  '346': { hasSubCode: false, code: { default: 'C26' } },
  '347': { hasSubCode: false, code: { default: 'C27' } },
  '351': { hasSubCode: false, code: { default: 'C28' } },
  '352': { hasSubCode: false, code: { default: 'C29' } },
  '353': { hasSubCode: false, code: { default: 'C30' } },
  '354': { hasSubCode: false, code: { default: 'C31' } },
  '361': { hasSubCode: false, code: { default: 'C32' } },
  '362': { hasSubCode: false, code: { default: 'C33' } },
  '363': { hasSubCode: false, code: { default: 'C34' } },
  '364': { hasSubCode: false, code: { default: 'C35' } },
  '365': { hasSubCode: false, code: { default: 'C36' } },
  '371': { hasSubCode: false, code: { default: 'C37' } },
  '372': { hasSubCode: false, code: { default: 'C38' } },
  '373': { hasSubCode: false, code: { default: 'C39' } },
  '374': { hasSubCode: false, code: { default: 'C40' } },
  '375': { hasSubCode: false, code: { default: 'C41' } },
  '376': { hasSubCode: false, code: { default: 'C42' } },
  '381': { hasSubCode: false, code: { default: 'C44.1' } },
  '382': { hasSubCode: false, code: { default: 'C44.2' } },
  '391': { hasSubCode: false, code: { default: 'C45' } },
  '392': { hasSubCode: false, code: { default: 'C46' } },
  '393': { hasSubCode: false, code: { default: 'C47' } },
  '411': { hasSubCode: false, code: { default: 'D1.1' } },
  '412': { hasSubCode: false, code: { default: 'D1.3' } },
  '413': { hasSubCode: false, code: { default: 'D1.4' } },
  '414': { hasSubCode: false, code: { default: 'D1.6' } },
  '415': { hasSubCode: false, code: { default: 'D1.8' } },
  '416': { hasSubCode: false, code: { default: 'D2' } },
  '417': { hasSubCode: false, code: { default: 'D3.1' } },
  '418': { hasSubCode: false, code: { default: 'D3.3' } },
  '421': { hasSubCode: false, code: { default: 'D4' } },
  '422': { hasSubCode: false, code: { default: 'D5' } },
  '423': { hasSubCode: false, code: { default: 'D6' } },
  '424': { hasSubCode: false, code: { default: 'D7.1' } },
  '425': { hasSubCode: false, code: { default: 'D7.2' } },
  '426': { hasSubCode: false, code: { default: 'D8' } },
  '427': { hasSubCode: false, code: { default: 'D9' } },
  '511': { hasSubCode: false, code: { default: 'E1' } },
  '520': { hasSubCode: false, code: { default: 'E3.1' } },
  '521': {
    hasSubCode: true,
    code: { default: 'E2', a: 'E4.1', b: 'E4.2', c: 'E4.3' }
  },
  '522': { hasSubCode: false, code: { default: 'E5' } },
  '531': { hasSubCode: false, code: { default: 'E6' } },
  '532': { hasSubCode: false, code: { default: 'E6' } },
  '533': { hasSubCode: false, code: { default: 'E7' } },
  '534': { hasSubCode: false, code: { default: 'E8' } },
  '541': { hasSubCode: true, code: { a: 'E9.1', b: 'E9.2' } },
  '542': { hasSubCode: true, code: { a: 'E10.1', b: 'E10.2' } },
  '543': { hasSubCode: true, code: { a: 'E11.1', b: 'E11.2' } },
  '544': { hasSubCode: true, code: { a: 'E12.1', b: 'E12.2' } },
  '551': { hasSubCode: false, code: { default: 'E14.1' } },
  '561': { hasSubCode: false, code: { default: 'E15' } },
  '562': { hasSubCode: false, code: { default: 'E16' } },
  '563': { hasSubCode: false, code: { default: 'E17' } },
  '564': { hasSubCode: false, code: { default: 'E18' } },
  '565': { hasSubCode: false, code: { default: 'E19' } },
  '566': { hasSubCode: false, code: { default: 'E20' } },
  '567': { hasSubCode: false, code: { default: 'E21' } },
  '571': { hasSubCode: false, code: { default: 'E22' } },
  '572': { hasSubCode: false, code: { default: 'E23' } },
  '573': { hasSubCode: false, code: { default: 'E24' } },
  '574': { hasSubCode: false, code: { default: 'E25' } },
  '575': { hasSubCode: false, code: { default: 'E26' } },
  '576': { hasSubCode: false, code: { default: 'E27' } },
  '611': { hasSubCode: false, code: { default: 'F1.1' } },
  '612': { hasSubCode: false, code: { default: 'F2.1' } },
  '613': { hasSubCode: false, code: { default: 'F4.2' } },
  '614': { hasSubCode: false, code: { default: 'F4.1' } },
  '615': { hasSubCode: false, code: { default: 'F5' } },
  '616': { hasSubCode: false, code: { default: 'F6' } },
  '621': { hasSubCode: false, code: { default: 'F7.1' } },
  '622': { hasSubCode: false, code: { default: 'F7.2' } },
  '623': { hasSubCode: false, code: { default: 'F8.1' } },
  '631': { hasSubCode: false, code: { default: 'F10' } },
  '632': { hasSubCode: false, code: { default: 'F11' } },
  '633': { hasSubCode: false, code: { default: 'F12' } },
  '641': { hasSubCode: false, code: { default: 'F13' } },
  '642': { hasSubCode: false, code: { default: 'F14' } },
  '643': { hasSubCode: false, code: { default: 'F13' } },
  '644': { hasSubCode: true, code: { default: 'F16', a: 'F17' } },
  '645': { hasSubCode: false, code: { default: 'F19' } },
  '646': { hasSubCode: false, code: { default: 'F15' } },
  '647': { hasSubCode: false, code: { default: 'F15' } },
  '648': { hasSubCode: false, code: { default: 'F13' } },
  '649': { hasSubCode: false, code: { default: 'F13' } },
  '650': { hasSubCode: false, code: { default: 'F18.1' } },
  '651': { hasSubCode: false, code: { default: 'F24.1' } },
  '652': { hasSubCode: false, code: { default: 'F24.2' } },
  '653': { hasSubCode: false, code: { default: 'F25' } },
  '661': { hasSubCode: false, code: { default: 'F26' } },
  '662': { hasSubCode: false, code: { default: 'F27.1' } },
  '663': { hasSubCode: false, code: { default: 'F28' } },
  '664': { hasSubCode: false, code: { default: 'F29' } },
  '665': { hasSubCode: true, code: { default: 'F30', a: 'F31' } },
  '666': { hasSubCode: false, code: { default: 'F32' } },
  '667': { hasSubCode: false, code: { default: 'F35' } },
  '671': { hasSubCode: false, code: { default: 'F37' } },
  '672': { hasSubCode: false, code: { default: 'F38' } },
  '673': { hasSubCode: false, code: { default: 'F39' } },
  '674': { hasSubCode: false, code: { default: 'F40' } },
  '675': { hasSubCode: false, code: { default: 'F42' } },
  '676': { hasSubCode: false, code: { default: 'F44' } },
  '677': { hasSubCode: true, code: { default: 'F46.1', a: 'F46.2' } },
  '678': { hasSubCode: false, code: { default: 'F47' } },
  '679': { hasSubCode: false, code: { default: 'F48' } },
  '681': { hasSubCode: false, code: { default: 'F50' } },
  '682': { hasSubCode: false, code: { default: 'F52' } },
  '683': { hasSubCode: false, code: { default: 'F53' } },
  '684': { hasSubCode: false, code: { default: 'F51' } },
  '685': { hasSubCode: false, code: { default: 'F54.1' } },
  '686': { hasSubCode: false, code: { default: 'F55.1' } },
  '690': { hasSubCode: false, code: { default: 'F56.1' } },
  '691': { hasSubCode: false, code: { default: 'F57.1' } },
  '701': { hasSubCode: false, code: { default: 'G1' } },
  '702': { hasSubCode: false, code: { default: 'G2' } },
  '703': { hasSubCode: false, code: { default: 'G3' } },
  '704': { hasSubCode: true, code: { default: 'G4', a: 'G5' } },
  '710': { hasSubCode: false, code: { default: 'G6' } },
  '711': { hasSubCode: false, code: { default: 'G7' } },
  '712': { hasSubCode: false, code: { default: 'G8' } },
  '715': { hasSubCode: false, code: { default: 'G9' } },
  '721': { hasSubCode: false, code: { default: 'G10' } },
  '722': { hasSubCode: false, code: { default: 'G11.1' } },
  '723': { hasSubCode: false, code: { default: 'G12' } },
  '724': { hasSubCode: false, code: { default: 'G13' } },
  '725': { hasSubCode: false, code: { default: 'G14' } },
  '726': { hasSubCode: false, code: { default: 'G15' } },
  '731': { hasSubCode: false, code: { default: 'G16' } },
  '733': { hasSubCode: false, code: { default: 'G17' } },
  '734': { hasSubCode: false, code: { default: 'G18' } },
  '741': { hasSubCode: false, code: { default: 'G19' } },
  '742': { hasSubCode: false, code: { default: 'G20' } },
  '771': { hasSubCode: true, code: { a: 'G41.1', b: 'G41.2' } },
  '772': {
    hasSubCode: true,
    code: { a: 'G23', b: 'G25', c: 'G24', e: 'G26', f: 'G27', g: 'G28' }
  },
  '773': {
    hasSubCode: true,
    code: { a: 'G29', b: 'G30', c: 'G31', d: 'G33', e: 'G34' }
  },
  '774': {
    hasSubCode: true,
    code: { a: 'G35', b: 'G36', c: 'G37', d: 'G38', e: 'G39', f: 'G40' }
  },
  '791': { hasSubCode: false, code: { default: 'G21' } },
  '792': { hasSubCode: false, code: { default: 'G22' } },
  '811': { hasSubCode: false, code: { default: 'H1' } },
  '812': { hasSubCode: false, code: { default: 'H2.1' } },
  '813': { hasSubCode: false, code: { default: 'H2.2' } },
  '814': { hasSubCode: false, code: { default: 'H3' } },
  '815': { hasSubCode: false, code: { default: 'H4' } },
  '816': { hasSubCode: false, code: { default: 'H5' } },
  '821': { hasSubCode: false, code: { default: 'H6' } },
  '822': { hasSubCode: false, code: { default: 'H7' } },
  '823': { hasSubCode: false, code: { default: 'H8' } },
  '824': { hasSubCode: false, code: { default: 'H9.1' } },
  '825': { hasSubCode: false, code: { default: 'H9.2' } },
  '826': { hasSubCode: false, code: { default: 'H10' } },
  '827': { hasSubCode: false, code: { default: 'H10' } },
  '828': { hasSubCode: false, code: { default: 'H11' } },
  '831': { hasSubCode: false, code: { default: 'H12.1' } },
  '832': { hasSubCode: false, code: { default: 'H12.2' } },
  '833': { hasSubCode: false, code: { default: 'H12.3' } },
  '834': { hasSubCode: false, code: { default: 'H12.4' } },
  '835': { hasSubCode: false, code: { default: 'H12.5' } },
  '836': { hasSubCode: false, code: { default: 'H12.7' } },
  '841': { hasSubCode: false, code: { default: 'H12.8' } },
  '842': { hasSubCode: false, code: { default: 'H12.9' } },
  '843': { hasSubCode: false, code: { default: 'H12.10' } },
  '844': { hasSubCode: false, code: { default: 'H13.2' } },
  '845': { hasSubCode: false, code: { default: 'H13.1' } },
  '848': { hasSubCode: false, code: { default: 'H14' } },
  '849': { hasSubCode: false, code: { default: 'H15' } },
  '851': { hasSubCode: false, code: { default: 'H17.1' } },
  '852': { hasSubCode: false, code: { default: 'H17.2' } },
  '853': { hasSubCode: false, code: { default: 'H17.3' } },
  '854': { hasSubCode: false, code: { default: 'H18' } },
  '855': { hasSubCode: true, code: { a: 'H20', b: 'H20' } },
  '856': { hasSubCode: true, code: { a: 'H19.1', b: 'H19.2' } },
  '861': {
    hasSubCode: true,
    code: { default: 'H22.1', a: 'H22.1', b: 'H22.2' }
  },
  '863': { hasSubCode: false, code: { default: 'H23.1' } },
  '871': { hasSubCode: false, code: { default: 'H24' } },
  '872': { hasSubCode: false, code: { default: 'H25' } },
  '880': { hasSubCode: false, code: { default: 'H26' } },
  '911': { hasSubCode: false, code: { default: 'I11' } },
  '916': { hasSubCode: false, code: { default: 'I6' } },
  '921': { hasSubCode: false, code: { default: 'F15' } },
  '931': { hasSubCode: false, code: { default: 'I7.1' } },
  '932': { hasSubCode: false, code: { default: 'I10.1' } },
  '935': { hasSubCode: false, code: { default: 'I8' } },
  '941': { hasSubCode: false, code: { default: 'I9' } },
  '1411': { hasSubCode: false, code: { default: 'A10' } },
  '5211': { hasSubCode: false, code: { default: 'E4.1' } },
  '5212': { hasSubCode: false, code: { default: 'E4.2' } },
  '5213': { hasSubCode: false, code: { default: 'E4.3' } },
  '5411': { hasSubCode: false, code: { default: 'E9.1' } },
  '5412': { hasSubCode: false, code: { default: 'E9.2' } },
  '5421': { hasSubCode: false, code: { default: 'E10.1' } },
  '5422': { hasSubCode: true, code: { default: 'E10.2', b: 'E10.2' } },
  '5431': { hasSubCode: false, code: { default: 'E11.1' } },
  '5432': { hasSubCode: false, code: { default: 'E11.2' } },
  '5441': { hasSubCode: false, code: { default: 'E12.1' } },
  '5442': { hasSubCode: false, code: { default: 'E12.2' } },
  '6225': { hasSubCode: false, code: { default: 'F7.3' } },
  '6441': { hasSubCode: false, code: { default: 'F17' } },
  '6651': { hasSubCode: false, code: { default: 'F31' } },
  '6679': { hasSubCode: false, code: { default: 'F34' } },
  '6771': { hasSubCode: false, code: { default: 'F46.2' } },
  '6811': { hasSubCode: false, code: { default: 'F50.1' } },
  '6812': { hasSubCode: false, code: { default: 'F50.2' } },
  '6813': { hasSubCode: false, code: { default: 'F50.3' } },
  '6814': { hasSubCode: false, code: { default: 'F50.4' } },
  '6815': { hasSubCode: false, code: { default: 'F50.5' } },
  '6816': { hasSubCode: false, code: { default: 'F50.6' } },
  '6817': { hasSubCode: false, code: { default: 'F50.7' } },
  '6818': { hasSubCode: false, code: { default: 'F50.8' } },
  '6819': { hasSubCode: false, code: { default: 'F50.9' } },
  '7041': { hasSubCode: false, code: { default: 'G5' } },
  '7711': { hasSubCode: false, code: { default: 'G41.1' } },
  '7712': { hasSubCode: false, code: { default: 'G41.2' } },
  '7721': { hasSubCode: false, code: { default: 'G23' } },
  '7722': { hasSubCode: false, code: { default: 'G25' } },
  '7723': { hasSubCode: false, code: { default: 'G24' } },
  '7724': { hasSubCode: false, code: { default: 'G26' } },
  '7725': { hasSubCode: false, code: { default: 'G27' } },
  '7726': { hasSubCode: false, code: { default: 'G28' } },
  '7731': { hasSubCode: false, code: { default: 'G29' } },
  '7732': { hasSubCode: false, code: { default: 'G30' } },
  '7733': { hasSubCode: false, code: { default: 'G31' } },
  '7734': { hasSubCode: false, code: { default: 'G33' } },
  '7735': { hasSubCode: false, code: { default: 'G34' } },
  '7741': { hasSubCode: false, code: { default: 'G35' } },
  '7742': { hasSubCode: false, code: { default: 'G36' } },
  '7743': { hasSubCode: false, code: { default: 'G37' } },
  '7744': { hasSubCode: false, code: { default: 'G38' } },
  '7745': { hasSubCode: false, code: { default: 'G39' } },
  '7746': { hasSubCode: false, code: { default: 'G40' } },
  '8551': { hasSubCode: false, code: { default: 'H20' } },
  '8552': { hasSubCode: false, code: { default: 'H20' } },
  '8561': { hasSubCode: false, code: { default: 'H19.1' } },
  '8562': { hasSubCode: false, code: { default: 'H19.2' } },
  '8611': { hasSubCode: false, code: { default: 'H22.1' } },
  '8612': { hasSubCode: false, code: { default: 'H22.2' } },
  '9512': { hasSubCode: false, code: { default: 'I17.1' } },
  '9901': { hasSubCode: false, code: { default: 'I15' } }
};

export default oldTrafficSignMapping;
