export const oldTrafficSignMapping = {
  '111. Mutka oikealle': 'A1.1 Mutka',
  '112. Mutka vasemmalle': 'A1.2 Mutka',
  '113. Mutkia, joista ensimmäinen oikealle': 'A2.1 Mutkia, joista ensimmäinen oikealle',
  '114. Mutkia, joista ensimmäinen vasemmalle': 'A2.2 Mutkia',
  '115. Jyrkkä alamäki': 'A3.2 Jyrkkä mäki',
  '116. Jyrkkä ylämäki': 'A3.1 Jyrkkä mäki',
  '121. Kapeneva tie': 'A4 Kapeneva tie',
  '122. Kaksisuuntainen liikenne': 'A5 Kaksisuuntainen liikenne',
  '131. Avattava silta': 'A6 Avattava silta',
  '132. Lautta, laituri tai ranta': 'A7 Lautta, laituri tai ranta',
  '133. Liikenneruuhka': 'A8 Liikenneruuhka',
  '141. Epätasainen tie': 'A9 Epätasainen tie',
  '141 a. Töyssyjä': 'A10 Töyssyjä',
  '142. Tietyö': 'A11 Tietyö',
  '143. Irtokiviä': 'A12 Irtokiviä',
  '144. Liukas ajorata': 'A13 Liukas ajorata',
  '147. Vaarallinen tien reuna': 'A14 Vaarallinen tienreuna',
  '151. Suojatien ennakkovaroitus': 'A15 Suojatien ennakkovaroitus',
  '152. Lapsia': 'A17 Lapsia',
  '153. Pyöräilijöitä': 'A18 Pyöräilijöitä',
  '154. Hiihtolatu': 'A19 Hiihtolatu',
  '155. Hirvieläimiä': 'A20.1 Hirvi',
  '156. Poroja': 'A20.2 Poro',
  '161. Tienristeys': 'A21 Tienristeys',
  '162. Sivutien risteys': 'A22.1 Sivutien risteys',
  '163. Sivutien risteys': 'A22.3 Sivutien risteys',
  '164. Sivutien risteys': 'A22.4 Sivutien risteys',
  '165. Liikennevalot': 'A23 Liikennevalot',
  '166. Liikenneympyrä': 'A24 Liikenneympyrä',
  '167. Raitiotie': 'A25 Raitiovaunu',
  '171. Rautatien tasoristeys ilman puomeja': 'A26 Rautatien tasoristeys ilman puomeja',
  '172. Rautatien tasoristeys, jossa on puomit':
    'A27 Rautatien tasoristeys, jossa on puomit',
  //'173. 174. 175. Rautatien tasoristeyksen lähestymismerkit': -
  '176. Yksiraiteisen rautatien tasoristeys': 'A29.1 Tasoristeys',
  '177. Kaksi- tai useampiraiteisen rautatien tasoristeys': 'A29.2 Tasoristeys',
  '181. Putoavia kiviä': 'A30 Putoavia kiviä',
  '182. Matalalla lentäviä lentokoneita': 'A31 Matalalla lentäviä lentokoneita',
  '183. Sivutuuli': 'A32 Sivutuuli',
  '189. Muu vaara': 'A33 Muu vaara',
  '211. Etuajo-oikeutettu tie': 'B1 Etuajo-oikeutettu tie',
  '212. Etuajo-oikeuden päättyminen': 'B2 Etuajo-oikeuden päättyminen',
  '221. Etuajo-oikeus kohdattaessa': 'B3 Etuajo-oikeus kohdattaessa',
  '222. Väistämisvelvollisuus kohdattaessa': 'B4 Väistämisvelvollisuus kohdattaessa',
  '231. Väistämisvelvollisuus risteyksessä': 'B5 Väistämisvelvollisuus risteyksessä',
  '232. Pakollinen pysäyttäminen': 'B6 Pakollinen pysäyttäminen',
  '311. Ajoneuvolla ajo kielletty': 'C1 Ajoneuvolla ajo kielletty',
  '312. Moottorikäyttöisellä ajoneuvolla ajo kielletty':
    'C2 Moottorikäyttöisellä ajoneuvolla ajo kielletty',
  '313. Kuorma- ja pakettiautolla ajo kielletty':
    'C3 Kuorma- ja pakettiautolla ajo kielletty',
  '314. Ajoneuvoyhdistelmällä ajo kielletty': 'C4 Ajoneuvoyhdistelmällä ajo kielletty',
  '315. Traktorilla ajo kielletty': 'C5 Traktorilla ajo kielletty',
  '316. Moottoripyörällä ajo kielletty': 'C6 Moottoripyörällä ajo kielletty',
  '317. Moottorikelkalla ajo kielletty': 'C7 Moottorikelkalla ajo kielletty',
  '318. Vaarallisten aineiden kuljetus kielletty':
    'C8 Vaarallisten aineiden kuljetus kielletty',
  '319. Linja-autolla ajo kielletty': 'C9 Linja-autolla ajo kielletty',
  '321. Mopolla ajo kielletty': 'C10 Mopolla ajo kielletty',
  '322. Polkupyörällä ja mopolla ajo kielletty':
    'C12 Polkupyörällä ja mopolla ajo kielletty',
  '323. Jalankulku kielletty': 'C13 Jalankulku kielletty',
  '324. Jalankulku sekä polkupyörällä ja mopolla ajo kielletty':
    'C15 Jalankulku ja polkupyörällä ja mopolla ajo kielletty',
  '325. Ratsastus kielletty': 'C16 Ratsastus kielletty',
  '331. Kielletty ajosuunta': 'C17 Kielletty ajosuunta',
  '332. Vasemmalle kääntyminen kielletty': 'C18 Vasemmalle kääntyminen kielletty',
  '333. Oikealle kääntyminen kielletty': 'C19 Oikealle kääntyminen kielletty',
  '334. U-käännös kielletty': 'C20 U-käännös kielletty',
  '341. Ajoneuvon suurin sallittu leveys': 'C21 Ajoneuvon suurin sallittu leveys',
  '342. Ajoneuvon suurin sallittu korkeus': 'C22 Ajoneuvon suurin sallittu korkeus',
  '343. Ajoneuvon tai ajoneuvoyhdistelmän suurin sallittu pituus':
    'C23 Ajoneuvon tai ajoneuvoyhdistelmän suurin sallittu pituus',
  '344. Ajoneuvon suurin sallittu massa': 'C24 Ajoneuvon suurin sallittu massa',
  '345. Ajoneuvoyhdistelmän suurin sallittu massa':
    'C25 Ajoneuvoyhdistelmän suurin sallittu massa',
  '346. Ajoneuvon suurin sallittu akselille kohdistuva massa':
    'C26 Ajoneuvon suurin sallittu akselille kohdistuva massa',
  '347. Ajoneuvon suurin sallittu telille kohdistuva massa':
    'C27 Ajoneuvon suurin sallittu telille kohdistuva massa',
  '351. Ohituskielto': 'C28 Ohituskielto',
  '352. Ohituskielto päättyy': 'C29 Ohituskielto päättyy',
  '353. Ohituskielto kuorma-autolla': 'C30 Ohituskielto kuorma-autolla',
  '354. Ohituskielto kuorma-autolla päättyy': 'C31 Ohituskielto kuorma-autolla päättyy',
  '361. Nopeusrajoitus': 'C32 Nopeusrajoitus',
  '362. Nopeusrajoitus päättyy': 'C33 Nopeusrajoitus päättyy',
  '363. Nopeusrajoitusalue': 'C34 Nopeusrajoitusalue',
  '364. Nopeusrajoitusalue päättyy': 'C35 Nopeusrajoitusalue päättyy',
  '365. Ajokaistakohtainen kielto tai rajoitus':
    'C36 Ajokaistakohtainen kielto, rajoitus tai määräys',
  '371. Pysäyttäminen kielletty': 'C37 Pysäyttäminen kielletty',
  '372. Pysäköinti kielletty': 'C38 Pysäköinti kielletty',
  '373. Pysäköintikieltoalue': 'C39 Pysäköintikieltoalue',
  '374. Pysäköintikieltoalue päättyy': 'C40 Pysäköintikieltoalue päättyy',
  '375. Taksiasema-alue': 'C41 Taksiasema-alue',
  '376. Taksin pysäyttämispaikka': 'C42 Taksin pysäyttämispaikka',
  '381. Vuoropysäköinti': 'C44.1 Vuoropysäköinti',
  '382. Vuoropysäköinti': 'C44.2 Vuoropysäköinti',
  '391. Pakollinen pysäyttäminen tullitarkastusta varten':
    'C45 Pakollinen pysäyttäminen tullitarkastusta varten',
  '392. Pakollinen pysäyttäminen tarkastusta varten':
    'C46 Pakollinen pysäyttäminen tarkastusta varten',
  '393. Moottorikäyttöisten ajoneuvojen vähimmäisetäisyys':
    'C47 Moottorikäyttöisten ajoneuvojen vähimmäisetäisyys',
  '411. Pakollinen ajosuunta': 'D1.1 Pakollinen ajosuunta',
  '412. Pakollinen ajosuunta': 'D1.3 Pakollinen ajosuunta',
  '413. Pakollinen ajosuunta': 'D1.4 Pakollinen ajosuunta',
  '414. Pakollinen ajosuunta': 'D1.6 Pakollinen ajosuunta',
  '415. Pakollinen ajosuunta': 'D1.8 Pakollinen ajosuunta',
  '416. Pakollinen kiertosuunta': 'D2 Pakollinen kiertosuunta',
  '417. Liikenteen jakaja': 'D3.1 Liikenteenjakaja',
  '418. Liikenteen jakaja': 'D3.3 Liikenteenjakaja',
  '421. Jalkakäytävä': 'D4 Jalkakäytävä',
  '422. Pyörätie': 'D5 Pyörätie',
  '423. Yhdistetty pyörätie ja jalkakäytävä': 'D6 Yhdistetty pyörätie ja jalkakäytävä',
  '424. Pyörätie ja jalkakäytävä rinnakkain': 'D7.1 Pyörätie ja jalkakäytävä rinnakkain',
  '425. Pyörätie ja jalkakäytävä rinnakkain': 'D7.2 Pyörätie ja jalkakäytävä rinnakkain',
  '426. Moottorikelkkailureitti': 'D8 Moottorikelkkailureitti',
  '427. Ratsastustie': 'D9 Ratsastustie',
  '511. Suojatie': 'E1 Suojatie',
  '520. Liityntäpysäköintipaikka': 'E3.1 Liityntäpysäköintipaikka',
  '521. Pysäköintipaikka': 'E2 Pysäköintipaikka',
  '521 a. Ajoneuvojen sijoitus pysäköintipaikalla':
    'E4.1 Ajoneuvojen sijoitus pysäköintipaikalla',
  '521 b. Ajoneuvojen sijoitus pysäköintipaikalla':
    'E4.2 Ajoneuvojen sijoitus pysäköintipaikalla',
  '521 c. Ajoneuvojen sijoitus pysäköintipaikalla':
    'E4.3 Ajoneuvojen sijoitus pysäköintipaikalla',
  '522. Kohtaamispaikka': 'E5 Kohtaamispaikka',
  '531. Paikallisliikenteen linja-auton pysäkki': 'E6 Linja-autopysäkki',
  '532. Kaukoliikenteen linja-auton pysäkki': 'E6 Linja-autopysäkki',
  '533. Raitiovaunun pysäkki': 'E7 Raitiovaunupysäkki',
  '534. Taksiasema': 'E8 Taksiasema',
  '541 a. Linja-autokaista': 'E9.1 Linja-autokaista',
  '541 b. Linja-autokaista': 'E9.2 Linja-autokaista',
  '542 a. Linja-autokaista päättyy': 'E10.1 Linja-autokaista päättyy',
  '542 b. Linja-autokaista päättyy': 'E10.2 Linja-autokaista päättyy',
  '543 a. Raitiovaunukaista': 'E11.1 Raitiovaunukaista',
  '543 b. Raitiovaunukaista': 'E11.2 Raitiovaunukaista',
  '544 a. Raitiovaunukaista päättyy': 'E12.1 Raitiovaunukaista päättyy',
  '544 b. Raitiovaunukaista päättyy': 'E12.2 Raitiovaunukaista päättyy',
  '551. Yksisuuntainen tie': 'E14.2. Yksisuuntainen tie',
  '561. Moottoritie': 'E15 Moottoritie',
  '562. Moottoritie päättyy': 'E16 Moottoritie päättyy',
  '563. Moottoriliikennetie': 'E17 Moottoriliikennetie',
  '564. Moottoriliikennetie päättyy': 'E18 Moottoriliikennetie päättyy',
  '565. Tunneli': 'E19 Tunneli',
  '566. Tunneli päättyy': 'E20 Tunneli päättyy',
  '567. Hätäpysäyttämispaikka': 'E21 Hätäpysäyttämispaikka',
  '571. Taajama': 'E22 Taajama',
  '572. Taajama päättyy': 'E23 Taajama päättyy',
  '573. Pihakatu': 'E24 Pihakatu',
  '574. Pihakatu päättyy': 'E25 Pihakatu päättyy',
  '575. Kävelykatu': 'E26 Kävelykatu',
  '576. Kävelykatu päättyy': 'E27 Kävelykatu päättyy',
  '611. Suunnistustaulu': 'F1.1 Suunnistustaulu',
  '612. Suunnistustaulu': 'F2.1 Suunnistustaulu',
  '613. Kiertotien suunnistustaulu': 'F4.2 Kiertotien suunnistustaulu',
  '614. Kiertotien suunnistustaulu': 'F4.1 Kiertotien suunnistustaulu',
  '615. Kiertotieopastus': 'F5 Kiertotieopastus',
  '616. Ajoreittiopastus': 'F6 Ajoreittiopastus',
  '621. Ajokaistaopastus': 'F7.1 Ajokaistaopastus',
  '622. Ajokaistaopastus': 'F7.2 Ajokaistaopastus',
  '623. Ajokaistan päättyminen': 'F8.1 Ajokaistan päättyminen',
  '631. Ajokaistan yläpuolinen viitta': 'F10 Ajokaistan yläpuolinen viitta',
  '632. Ajokaistan yläpuolinen viitta': 'F11 Ajokaistan yläpuolinen viitta',
  '633. Ajokaistan yläpuolinen erkanemisviitta':
    'F12 Ajokaistan yläpuolinen erkanemisviitta',
  '641. Tienviitta': 'F13 Tienviitta',
  '642. Erkanemisviitta': 'F14 Erkanemisviitta',
  '643. Yksityisen tien viitta': 'F13 Tienviitta',
  '644. Osoiteviitta': 'F16 Osoiteviitta',
  '644 a. Osoiteviittan ennakkomerkki': 'F17 Osoiteviitan ennakkomerkki',
  '645. Kevyen liikenteen viitta': 'F19 Jalankulun viitta',
  '646. Kiertotien viitta': 'F13 Tienviitta',
  '647. Kiertotien viitta': 'F15 Kiertotien viitta',
  '648. Paikalliskohteen viitta': 'F13 Tienviitta',
  '649. Moottori- ja moottoriliikennetien viitta': 'F13 Tienviitta',
  '650. Liityntäpysäköintiviitta': 'F18 Liityntäpysäköintiviitta',
  '651. Umpitie': 'F24.1 Umpitie',
  '652. Umpitie': 'F24.2 Umpitie',
  '653. Enimmäisnopeussuositus': 'F25 Enimmäisnopeussuositus',
  '661. Etäisyystaulu': 'F26 Etäisyystaulu',
  '662. Paikannimi': 'F27.1 Paikannimi',
  '663. Kansainvälisen pääliikenneväylän numero':
    'F28 Kansainvälisen pääliikenneväylän numero',
  '664. Valtatien numero': 'F29 Valtatien numero',
  '665. Kantatien numero': 'F30 Kantatien numero',
  '665 a. Seututien numero': 'F31 Seututien numero',
  '666. Muun yleisen tien numero': 'F32 Muun maantien numero',
  '667. Opastus numeron tarkoittamalle tielle':
    'F35 Opastus merkin tarkoittamalle tielle',
  '671. Moottoritien tunnus': 'F37 Moottoritien tunnus',
  '672. Moottoriliikennetien tunnus': 'F38 Moottoriliikennetien tunnus',
  '673. Lentoasema': 'F39 Lentoasema',
  '674. Autolautta': 'F40 Autolautta',
  '675. Tavarasatama': 'F42 Tavarasatama',
  '676. Teollisuusalue': 'F44 Teollisuusalue tai yritysalue',
  '677. Pysäköinti': 'F46.1 Pysäköinti',
  '677 a. Katettu pysäköinti': 'F46.2 Pysäköinti',
  '678. Rautatieasema': 'F47 Rautatieasema',
  '679. Linja-autoasema': 'F48 Linja-autoasema',
  '681. Tietyille ajoneuvoille tai ajoneuvoyhdistelmille tarkoitettu reitti':
    'F50 Tietylle ajoneuvolle tarkoitettu reitti',
  '682. Jalankulkijoille tarkoitettu reitti': 'F52 Jalankulkijalle tarkoitettu reitti',
  '683. Vammaisille tarkoitettu reitti': 'F53 Esteetön reitti',
  '684. Vaarallisten aineiden kuljetuksille tarkoitettu reitti':
    'F51 Vaarallisten aineiden kuljetukselle tarkoitettu reitti',
  '685. Reitti, jolla on portaat': 'F54 Reitti, jolla on portaat',
  '686. Reitti ilman portaita': 'F55 Reitti ilman portaita',
  '690. Hätäuloskäynti': 'F56 Hätäuloskäynti',
  '691. Poistumisreitti': 'F57 Poistumisreitti',
  '701. Palvelukohteen opastustaulu': 'G1 Palvelukohteen opastustaulu',
  '702. Palvelukohteen opastustaulu': 'G2 Palvelukohteen opastustaulu',
  '703. Palvelukohteen erkanemisviitta': 'G3 Palvelukohteen erkanemisviitta',
  '704. Palvelukohteen osoiteviitta': 'G4 Palvelukohteen osoiteviitta',
  '704 a. Palvelukohteen osoiteviittan ennakkomerkki':
    'G5 Palvelukohteen osoiteviitan ennakkomerkki',
  '710. Radioaseman taajuus': 'G6 Radioaseman taajuus',
  '711. Opastuspiste': 'G7 Opastuspiste',
  '712. Opastustoimisto': 'G8 Opastustoimisto',
  '715. Ensiapu': 'G9 Ensiapu',
  '721. Autokorjaamo': 'G10 Autokorjaamo',
  '722. Huoltoasema': 'G11.1 Polttoaineen jakelu',
  '723. Hotelli tai motelli': 'G12 Hotelli tai motelli',
  '724. Ruokailupaikka': 'G13 Ruokailupaikka',
  '725. Kahvila tai pikaruokapaikka': 'G14 Kahvila tai pikaruokapaikka',
  '726. Käymälä': 'G15 Käymälä',
  '731. Retkeilymaja': 'G16 Retkeilymaja',
  '733. Leirintäalue': 'G17 Leirintäalue',
  '734. Matkailuajoneuvoalue': 'G18 Matkailuajoneuvoalue',
  '741. Levähdysalue': 'G19 Levähdysalue',
  '742. Ulkoilualue': 'G20 Ulkoilualue',
  '791. Hätäpuhelin': 'G21 Hätäpuhelin',
  '792. Sammutin': 'G22 Sammutin',
  '771 a. Matkailutie': 'G41.1 Matkailutie',
  '771 b. Matkailutie': 'G41.2 Matkailutie',
  '772 a. Museo tai historiallinen rakennus': 'G23 Museo tai historiallinen rakennus',
  '772 b. Maailmanperintökohde': 'G24 Maailmanperintökohde',
  '772 c. Luontokohde': 'G25 Luontokohde',
  '772 d. Näköalapaikka': 'G26 Näköalapaikka',
  '772 e. Eläintarha tai -puisto': 'G27 Eläintarha tai -puisto',
  '772 f. Muu nähtävyys': 'G28 Muu nähtävyys',
  '773 a. Uintipaikka': 'G29 Uintipaikka',
  '773 b. Kalastuspaikka': 'G30 Kalastuspaikka',
  '773 c. Hiihtohissi': 'G31 Hiihtohissi',
  '773 d. Golfkenttä': 'G33 Golfkenttä',
  '773 e. Huvi- tai teemapuisto': 'G34 Huvi- ja teemapuisto',
  '774 a. Mökkimajoitus': 'G35 Mökkimajoitus',
  '774 b. Aamiaismajoitus': 'G36 Aamiaismajoitus',
  '774 c. Suoramyyntipaikka': 'G37 Suoramyyntipaikka',
  '774 d. Käsityöpaja': 'G38 Käsityöpaja',
  '774 e. Kotieläinpiha': 'G39 Kotieläinpiha',
  '774 f. Ratsastuspaikka': 'G40 Ratsastuspaikka',
  '811. Kohde risteävällä tiellä': 'H1 Kohde risteävässä suunnassa',
  '812. Kohde nuolen suunnassa': 'H2.1 Kohde nuolen suunnassa',
  '813. Kohde nuolen suunnassa': 'H2.2 Kohde nuolen suunnassa',
  '814. Vaikutusalueen pituus': 'H3 Vaikutusalueen pituus',
  '815. Etäisyys kohteeseen': 'H4 Etäisyys kohteeseen',
  '816. Etäisyys pakolliseen pysäyttämiseen': 'H5 Etäisyys pakolliseen pysäyttämiseen',
  '821. Vapaa leveys': 'H6 Vapaa leveys',
  '822. Vapaa korkeus': 'H7 Vapaa korkeus',
  '823. Sähköjohdon korkeus': 'H8 Sähköjohdon korkeus',
  '824. Vaikutusalue molempiin suuntiin': 'H9.1 Vaikutusalue molempiin suuntiin',
  '825. Vaikutusalue molempiin suuntiin': 'H9.2 Vaikutusalue molempiin suuntiin',
  '826. Vaikutusalue nuolen suuntaan': 'H10 Vaikutusalue nuolen suuntaan',
  '827. Vaikutusalue alkaa': 'H10 Vaikutusalue nuolen suuntaan',
  '828. Vaikutusalue päättyy': 'H11 Vaikutusalue päättyy',
  '831. Henkilöauto': 'H12.1 Henkilöauto',
  '832. Linja-auto': 'H12.2 Linja-auto',
  '833. Kuorma-auto': 'H12.3 Kuorma-auto',
  '834. Pakettiauto': 'H12.4 Pakettiauto',
  '835. Matkailuajoneuvo': 'H12.5 Matkailuperävaunu',
  '836. Invalidin ajoneuvo': 'H12.7 Invalidin ajoneuvo',
  '841. Moottoripyörä': 'H12.8 Moottoripyörä',
  '842. Mopo': 'H12.9 Mopo',
  '843. Polkupyörä': 'H12.10 Polkupyörä',
  '844. Pysäköintitapa': 'H13.2 Pysäköintitapa',
  '845. Pysäköintitapa': 'H13.1 Pysäköintitapa',
  '848. Kielto ryhmän A vaarallisten aineiden kuljetukselle':
    'H14 Kielto ryhmän A vaarallisten aineiden kuljetukselle',
  '849. Läpiajokielto ryhmän B vaarallisten aineiden kuljetukselle':
    'H15 Läpiajokielto ryhmän B vaarallisten aineiden kuljetukselle',
  '851. Voimassaoloaika': 'H17.1 Voimassaoloaika arkisin',
  '852. Voimassaoloaika': 'H17.2 Voimassaoloaika lauantaisin',
  '853. Voimassaoloaika': 'H17.3 Voimassaoloaika sunnuntaisin ja pyhinä',
  '854. Aikarajoitus': 'H18 Aikarajoitus',
  '855 a. Maksullinen pysäköinti': 'H20 Maksullinen pysäköinti',
  '855 b. Maksullinen pysäköinti': 'H20 Maksullinen pysäköinti',
  '856 a. Pysäköintikiekon käyttövelvollisuus':
    'H19.1 Pysäköintiajan alkamisen osoittamisvelvollisuus',
  '856 b. Pysäköintikiekon käyttövelvollisuus':
    'H19.2 Pysäköintiajan alkamisen osoittamisvelvollisuus',
  '861 a. Etuajo-oikeutetun liikenteen suunta':
    'H22.1 Etuajo-oikeutetun liikenteen suunta',
  '861 b. Etuajo-oikeutetun liikenteen suunta':
    'H22.2 Etuajo-oikeutetun liikenteen suunta',
  '862. Tukkitie': 99,
  '863. Kaksisuuntainen pyörätie': 'H23.1 Kaksisuuntainen pyörätie',
  '871. Tekstillinen lisäkilpi': 'H24 Tekstillinen lisäkilpi',
  '872. Tekstillinen lisäkilpi Huoltoajo sallittu': 'H25 Huoltoajo sallittu',
  '880. Hätäpuhelin ja sammutin': 'H26 Hätäpuhelin ja sammutin'
};

interface TrafficSignMapping {
  [key: string]: {
    hasSubCode: boolean;
    code: {
      [key: string]: string;
    };
  };
}

export const trafficSignMapping: TrafficSignMapping = {
  '10': { hasSubCode: false, code: { default: 'F27.1' } },
  '11': { hasSubCode: false, code: { default: 'F27.1' } },
  '111': { hasSubCode: false, code: { default: 'A1.1' } },
  '112': { hasSubCode: false, code: { default: 'A1.2' } },
  '113': { hasSubCode: false, code: { default: 'A2.1' } },
  '114': { hasSubCode: false, code: { default: 'A2.2' } },
  '115': { hasSubCode: false, code: { default: 'A3.2' } },
  '116': { hasSubCode: false, code: { default: 'A3.1' } },
  '121': { hasSubCode: false, code: { default: 'A4' } },
  '122': { hasSubCode: false, code: { default: 'A5' } },
  '131': { hasSubCode: false, code: { default: 'A6' } },
  '132': { hasSubCode: false, code: { default: 'A7' } },
  '133': { hasSubCode: false, code: { default: 'A8' } },
  '141': { hasSubCode: true, code: { default: 'A9', a: 'A10' } },
  '142': { hasSubCode: false, code: { default: 'A11' } },
  '143': { hasSubCode: false, code: { default: 'A12' } },
  '144': { hasSubCode: false, code: { default: 'A13' } },
  '147': { hasSubCode: false, code: { default: 'A14' } },
  '151': { hasSubCode: false, code: { default: 'A15' } },
  '152': { hasSubCode: false, code: { default: 'A17' } },
  '153': { hasSubCode: false, code: { default: 'A18' } },
  '154': { hasSubCode: false, code: { default: 'A19' } },
  '155': { hasSubCode: false, code: { default: 'A20.1' } },
  '156': { hasSubCode: false, code: { default: 'A20.2' } },
  '161': { hasSubCode: false, code: { default: 'A21' } },
  '162': { hasSubCode: false, code: { default: 'A22.1' } },
  '163': { hasSubCode: false, code: { default: 'A22.3' } },
  '164': { hasSubCode: false, code: { default: 'A22.4' } },
  '165': { hasSubCode: false, code: { default: 'A23' } },
  '166': { hasSubCode: false, code: { default: 'A24' } },
  '167': { hasSubCode: false, code: { default: 'A25' } },
  '171': { hasSubCode: false, code: { default: 'A26' } },
  '172': { hasSubCode: false, code: { default: 'A27' } },
  '173': { hasSubCode: false, code: { default: 'A28.1' } },
  '174': { hasSubCode: false, code: { default: 'A28.2' } },
  '175': { hasSubCode: false, code: { default: 'A28.3' } },
  '176': { hasSubCode: false, code: { default: 'A29.1' } },
  '177': { hasSubCode: false, code: { default: 'A29.2' } },
  '181': { hasSubCode: false, code: { default: 'A30' } },
  '182': { hasSubCode: false, code: { default: 'A31' } },
  '183': { hasSubCode: false, code: { default: 'A32' } },
  '189': { hasSubCode: false, code: { default: 'A33' } },
  '211': { hasSubCode: false, code: { default: 'B1' } },
  '212': { hasSubCode: false, code: { default: 'B2' } },
  '221': { hasSubCode: false, code: { default: 'B3' } },
  '222': { hasSubCode: false, code: { default: 'B4' } },
  '231': { hasSubCode: false, code: { default: 'B5' } },
  '232': { hasSubCode: false, code: { default: 'B6' } },
  '311': { hasSubCode: false, code: { default: 'C1' } },
  '312': { hasSubCode: false, code: { default: 'C2' } },
  '313': { hasSubCode: false, code: { default: 'C3' } },
  '314': { hasSubCode: false, code: { default: 'C4' } },
  '315': { hasSubCode: false, code: { default: 'C5' } },
  '316': { hasSubCode: false, code: { default: 'C6' } },
  '317': { hasSubCode: false, code: { default: 'C7' } },
  '318': { hasSubCode: false, code: { default: 'C8' } },
  '319': { hasSubCode: false, code: { default: 'C9' } },
  '321': { hasSubCode: false, code: { default: 'C10' } },
  '322': { hasSubCode: false, code: { default: 'C12' } },
  '323': { hasSubCode: false, code: { default: 'C13' } },
  '324': { hasSubCode: false, code: { default: 'C15' } },
  '325': { hasSubCode: false, code: { default: 'C16' } },
  '331': { hasSubCode: false, code: { default: 'C17' } },
  '332': { hasSubCode: false, code: { default: 'C18' } },
  '333': { hasSubCode: false, code: { default: 'C19' } },
  '334': { hasSubCode: false, code: { default: 'C20' } },
  '341': { hasSubCode: false, code: { default: 'C21' } },
  '342': { hasSubCode: false, code: { default: 'C22' } },
  '343': { hasSubCode: false, code: { default: 'C23' } },
  '344': { hasSubCode: false, code: { default: 'C24' } },
  '345': { hasSubCode: false, code: { default: 'C25' } },
  '346': { hasSubCode: false, code: { default: 'C26' } },
  '347': { hasSubCode: false, code: { default: 'C27' } },
  '351': { hasSubCode: false, code: { default: 'C28' } },
  '352': { hasSubCode: false, code: { default: 'C29' } },
  '353': { hasSubCode: false, code: { default: 'C30' } },
  '354': { hasSubCode: false, code: { default: 'C31' } },
  '361': { hasSubCode: false, code: { default: 'C32' } },
  '362': { hasSubCode: false, code: { default: 'C33' } },
  '363': { hasSubCode: false, code: { default: 'C34' } },
  '364': { hasSubCode: false, code: { default: 'C35' } },
  '365': { hasSubCode: false, code: { default: 'C36' } },
  '371': { hasSubCode: false, code: { default: 'C37' } },
  '372': { hasSubCode: false, code: { default: 'C38' } },
  '373': { hasSubCode: false, code: { default: 'C39' } },
  '374': { hasSubCode: false, code: { default: 'C40' } },
  '375': { hasSubCode: false, code: { default: 'C41' } },
  '376': { hasSubCode: false, code: { default: 'C42' } },
  '381': { hasSubCode: false, code: { default: 'C44.1' } },
  '382': { hasSubCode: false, code: { default: 'C44.2' } },
  '391': { hasSubCode: false, code: { default: 'C45' } },
  '392': { hasSubCode: false, code: { default: 'C46' } },
  '393': { hasSubCode: false, code: { default: 'C47' } },
  '411': { hasSubCode: false, code: { default: 'D1.1' } },
  '412': { hasSubCode: false, code: { default: 'D1.3' } },
  '413': { hasSubCode: false, code: { default: 'D1.4' } },
  '414': { hasSubCode: false, code: { default: 'D1.6' } },
  '415': { hasSubCode: false, code: { default: 'D1.8' } },
  '416': { hasSubCode: false, code: { default: 'D2' } },
  '417': { hasSubCode: false, code: { default: 'D3.1' } },
  '418': { hasSubCode: false, code: { default: 'D3.3' } },
  '421': { hasSubCode: false, code: { default: 'D4' } },
  '422': { hasSubCode: false, code: { default: 'D5' } },
  '423': { hasSubCode: false, code: { default: 'D6' } },
  '424': { hasSubCode: false, code: { default: 'D7.1' } },
  '425': { hasSubCode: false, code: { default: 'D7.2' } },
  '426': { hasSubCode: false, code: { default: 'D8' } },
  '427': { hasSubCode: false, code: { default: 'D9' } },
  '511': { hasSubCode: false, code: { default: 'E1' } },
  '520': { hasSubCode: false, code: { default: 'E3.1' } },
  '521': {
    hasSubCode: true,
    code: { default: 'E2', a: 'E4.1', b: 'E4.2', c: 'E4.3' }
  },
  '522': { hasSubCode: false, code: { default: 'E5' } },
  '531': { hasSubCode: false, code: { default: 'E6' } },
  '532': { hasSubCode: false, code: { default: 'E6' } },
  '533': { hasSubCode: false, code: { default: 'E7' } },
  '534': { hasSubCode: false, code: { default: 'E8' } },
  '541': { hasSubCode: true, code: { a: 'E9.1', b: 'E9.2' } },
  '542': { hasSubCode: true, code: { a: 'E10.1', b: 'E10.2' } },
  '543': { hasSubCode: true, code: { a: 'E11.1', b: 'E11.2' } },
  '544': { hasSubCode: true, code: { a: 'E12.1', b: 'E12.2' } },
  '551': { hasSubCode: false, code: { default: 'E14.1' } },
  '561': { hasSubCode: false, code: { default: 'E15' } },
  '562': { hasSubCode: false, code: { default: 'E16' } },
  '563': { hasSubCode: false, code: { default: 'E17' } },
  '564': { hasSubCode: false, code: { default: 'E18' } },
  '565': { hasSubCode: false, code: { default: 'E19' } },
  '566': { hasSubCode: false, code: { default: 'E20' } },
  '567': { hasSubCode: false, code: { default: 'E21' } },
  '571': { hasSubCode: false, code: { default: 'E22' } },
  '572': { hasSubCode: false, code: { default: 'E23' } },
  '573': { hasSubCode: false, code: { default: 'E24' } },
  '574': { hasSubCode: false, code: { default: 'E25' } },
  '575': { hasSubCode: false, code: { default: 'E26' } },
  '576': { hasSubCode: false, code: { default: 'E27' } },
  '611': { hasSubCode: false, code: { default: 'F1.1' } },
  '612': { hasSubCode: false, code: { default: 'F2.1' } },
  '613': { hasSubCode: false, code: { default: 'F4.2' } },
  '614': { hasSubCode: false, code: { default: 'F4.1' } },
  '615': { hasSubCode: false, code: { default: 'F5' } },
  '616': { hasSubCode: false, code: { default: 'F6' } },
  '621': { hasSubCode: false, code: { default: 'F7.1' } },
  '622': { hasSubCode: false, code: { default: 'F7.2' } },
  '623': { hasSubCode: false, code: { default: 'F8.1' } },
  '631': { hasSubCode: false, code: { default: 'F10' } },
  '632': { hasSubCode: false, code: { default: 'F11' } },
  '633': { hasSubCode: false, code: { default: 'F12' } },
  '641': { hasSubCode: false, code: { default: 'F13' } },
  '642': { hasSubCode: false, code: { default: 'F14' } },
  '643': { hasSubCode: false, code: { default: 'F13' } },
  '644': { hasSubCode: true, code: { default: 'F16', a: 'F17' } },
  '645': { hasSubCode: false, code: { default: 'F19' } },
  '646': { hasSubCode: false, code: { default: 'F15' } },
  '647': { hasSubCode: false, code: { default: 'F15' } },
  '648': { hasSubCode: false, code: { default: 'F13' } },
  '649': { hasSubCode: false, code: { default: 'F13' } },
  '650': { hasSubCode: false, code: { default: 'F18.1' } },
  '651': { hasSubCode: false, code: { default: 'F24.1' } },
  '652': { hasSubCode: false, code: { default: 'F24.2' } },
  '653': { hasSubCode: false, code: { default: 'F25' } },
  '661': { hasSubCode: false, code: { default: 'F26' } },
  '662': { hasSubCode: false, code: { default: 'F27.1' } },
  '663': { hasSubCode: false, code: { default: 'F28' } },
  '664': { hasSubCode: false, code: { default: 'F29' } },
  '665': { hasSubCode: true, code: { default: 'F30', a: 'F31' } },
  '666': { hasSubCode: false, code: { default: 'F32' } },
  '667': { hasSubCode: false, code: { default: 'F35' } },
  '671': { hasSubCode: false, code: { default: 'F37' } },
  '672': { hasSubCode: false, code: { default: 'F38' } },
  '673': { hasSubCode: false, code: { default: 'F39' } },
  '674': { hasSubCode: false, code: { default: 'F40' } },
  '675': { hasSubCode: false, code: { default: 'F42' } },
  '676': { hasSubCode: false, code: { default: 'F44' } },
  '677': { hasSubCode: true, code: { default: 'F46.1', a: 'F46.2' } },
  '678': { hasSubCode: false, code: { default: 'F47' } },
  '679': { hasSubCode: false, code: { default: 'F48' } },
  '681': { hasSubCode: false, code: { default: 'F50' } },
  '682': { hasSubCode: false, code: { default: 'F52' } },
  '683': { hasSubCode: false, code: { default: 'F53' } },
  '684': { hasSubCode: false, code: { default: 'F51' } },
  '685': { hasSubCode: false, code: { default: 'F54.1' } },
  '686': { hasSubCode: false, code: { default: 'F55.1' } },
  '690': { hasSubCode: false, code: { default: 'F56.1' } },
  '691': { hasSubCode: false, code: { default: 'F57.1' } },
  '701': { hasSubCode: false, code: { default: 'G1' } },
  '702': { hasSubCode: false, code: { default: 'G2' } },
  '703': { hasSubCode: false, code: { default: 'G3' } },
  '704': { hasSubCode: true, code: { default: 'G4', a: 'G5' } },
  '710': { hasSubCode: false, code: { default: 'G6' } },
  '711': { hasSubCode: false, code: { default: 'G7' } },
  '712': { hasSubCode: false, code: { default: 'G8' } },
  '715': { hasSubCode: false, code: { default: 'G9' } },
  '721': { hasSubCode: false, code: { default: 'G10' } },
  '722': { hasSubCode: false, code: { default: 'G11.1' } },
  '723': { hasSubCode: false, code: { default: 'G12' } },
  '724': { hasSubCode: false, code: { default: 'G13' } },
  '725': { hasSubCode: false, code: { default: 'G14' } },
  '726': { hasSubCode: false, code: { default: 'G15' } },
  '731': { hasSubCode: false, code: { default: 'G16' } },
  '733': { hasSubCode: false, code: { default: 'G17' } },
  '734': { hasSubCode: false, code: { default: 'G18' } },
  '741': { hasSubCode: false, code: { default: 'G19' } },
  '742': { hasSubCode: false, code: { default: 'G20' } },
  '771': { hasSubCode: true, code: { a: 'G41.1', b: 'G41.2' } },
  '772': {
    hasSubCode: true,
    code: { a: 'G23', b: 'G25', c: 'G24', e: 'G26', f: 'G27', g: 'G28' }
  },
  '773': {
    hasSubCode: true,
    code: { a: 'G29', b: 'G30', c: 'G31', d: 'G33', e: 'G34' }
  },
  '774': {
    hasSubCode: true,
    code: { a: 'G35', b: 'G36', c: 'G37', d: 'G38', e: 'G39', f: 'G40' }
  },
  '791': { hasSubCode: false, code: { default: 'G21' } },
  '792': { hasSubCode: false, code: { default: 'G22' } },
  '811': { hasSubCode: false, code: { default: 'H1' } },
  '812': { hasSubCode: false, code: { default: 'H2.1' } },
  '813': { hasSubCode: false, code: { default: 'H2.2' } },
  '814': { hasSubCode: false, code: { default: 'H3' } },
  '815': { hasSubCode: false, code: { default: 'H4' } },
  '816': { hasSubCode: false, code: { default: 'H5' } },
  '821': { hasSubCode: false, code: { default: 'H6' } },
  '822': { hasSubCode: false, code: { default: 'H7' } },
  '823': { hasSubCode: false, code: { default: 'H8' } },
  '824': { hasSubCode: false, code: { default: 'H9.1' } },
  '825': { hasSubCode: false, code: { default: 'H9.2' } },
  '826': { hasSubCode: false, code: { default: 'H10' } },
  '827': { hasSubCode: false, code: { default: 'H10' } },
  '828': { hasSubCode: false, code: { default: 'H11' } },
  '831': { hasSubCode: false, code: { default: 'H12.1' } },
  '832': { hasSubCode: false, code: { default: 'H12.2' } },
  '833': { hasSubCode: false, code: { default: 'H12.3' } },
  '834': { hasSubCode: false, code: { default: 'H12.4' } },
  '835': { hasSubCode: false, code: { default: 'H12.5' } },
  '836': { hasSubCode: false, code: { default: 'H12.7' } },
  '841': { hasSubCode: false, code: { default: 'H12.8' } },
  '842': { hasSubCode: false, code: { default: 'H12.9' } },
  '843': { hasSubCode: false, code: { default: 'H12.10' } },
  '844': { hasSubCode: false, code: { default: 'H13.2' } },
  '845': { hasSubCode: false, code: { default: 'H13.1' } },
  '848': { hasSubCode: false, code: { default: 'H14' } },
  '849': { hasSubCode: false, code: { default: 'H15' } },
  '851': { hasSubCode: false, code: { default: 'H17.1' } },
  '852': { hasSubCode: false, code: { default: 'H17.2' } },
  '853': { hasSubCode: false, code: { default: 'H17.3' } },
  '854': { hasSubCode: false, code: { default: 'H18' } },
  '855': { hasSubCode: true, code: { a: 'H20', b: 'H20' } },
  '856': { hasSubCode: true, code: { a: 'H19.1', b: 'H19.2' } },
  '861': {
    hasSubCode: true,
    code: { default: 'H22.1', a: 'H22.1', b: 'H22.2' }
  },
  '863': { hasSubCode: false, code: { default: 'H23.1' } },
  '871': { hasSubCode: false, code: { default: 'H24' } },
  '872': { hasSubCode: false, code: { default: 'H25' } },
  '880': { hasSubCode: false, code: { default: 'H26' } },
  '911': { hasSubCode: false, code: { default: 'I11' } },
  '916': { hasSubCode: false, code: { default: 'I6' } },
  '921': { hasSubCode: false, code: { default: 'F15' } },
  '931': { hasSubCode: false, code: { default: 'I7.1' } },
  '932': { hasSubCode: false, code: { default: 'I10.1' } },
  '935': { hasSubCode: false, code: { default: 'I8' } },
  '941': { hasSubCode: false, code: { default: 'I9' } },
  '1411': { hasSubCode: false, code: { default: 'A10' } },
  '5211': { hasSubCode: false, code: { default: 'E4.1' } },
  '5212': { hasSubCode: false, code: { default: 'E4.2' } },
  '5213': { hasSubCode: false, code: { default: 'E4.3' } },
  '5411': { hasSubCode: false, code: { default: 'E9.1' } },
  '5412': { hasSubCode: false, code: { default: 'E9.2' } },
  '5421': { hasSubCode: false, code: { default: 'E10.1' } },
  '5422': { hasSubCode: true, code: { default: 'E10.2', b: 'E10.2' } },
  '5431': { hasSubCode: false, code: { default: 'E11.1' } },
  '5432': { hasSubCode: false, code: { default: 'E11.2' } },
  '5441': { hasSubCode: false, code: { default: 'E12.1' } },
  '5442': { hasSubCode: false, code: { default: 'E12.2' } },
  '6225': { hasSubCode: false, code: { default: 'F7.3' } },
  '6441': { hasSubCode: false, code: { default: 'F17' } },
  '6651': { hasSubCode: false, code: { default: 'F31' } },
  '6679': { hasSubCode: false, code: { default: 'F34' } },
  '6771': { hasSubCode: false, code: { default: 'F46.2' } },
  '6811': { hasSubCode: false, code: { default: 'F50.1' } },
  '6812': { hasSubCode: false, code: { default: 'F50.2' } },
  '6813': { hasSubCode: false, code: { default: 'F50.3' } },
  '6814': { hasSubCode: false, code: { default: 'F50.4' } },
  '6815': { hasSubCode: false, code: { default: 'F50.5' } },
  '6816': { hasSubCode: false, code: { default: 'F50.6' } },
  '6817': { hasSubCode: false, code: { default: 'F50.7' } },
  '6818': { hasSubCode: false, code: { default: 'F50.8' } },
  '6819': { hasSubCode: false, code: { default: 'F50.9' } },
  '7041': { hasSubCode: false, code: { default: 'G5' } },
  '7711': { hasSubCode: false, code: { default: 'G41.1' } },
  '7712': { hasSubCode: false, code: { default: 'G41.2' } },
  '7721': { hasSubCode: false, code: { default: 'G23' } },
  '7722': { hasSubCode: false, code: { default: 'G25' } },
  '7723': { hasSubCode: false, code: { default: 'G24' } },
  '7724': { hasSubCode: false, code: { default: 'G26' } },
  '7725': { hasSubCode: false, code: { default: 'G27' } },
  '7726': { hasSubCode: false, code: { default: 'G28' } },
  '7731': { hasSubCode: false, code: { default: 'G29' } },
  '7732': { hasSubCode: false, code: { default: 'G30' } },
  '7733': { hasSubCode: false, code: { default: 'G31' } },
  '7734': { hasSubCode: false, code: { default: 'G33' } },
  '7735': { hasSubCode: false, code: { default: 'G34' } },
  '7741': { hasSubCode: false, code: { default: 'G35' } },
  '7742': { hasSubCode: false, code: { default: 'G36' } },
  '7743': { hasSubCode: false, code: { default: 'G37' } },
  '7744': { hasSubCode: false, code: { default: 'G38' } },
  '7745': { hasSubCode: false, code: { default: 'G39' } },
  '7746': { hasSubCode: false, code: { default: 'G40' } },
  '8551': { hasSubCode: false, code: { default: 'H20' } },
  '8552': { hasSubCode: false, code: { default: 'H20' } },
  '8561': { hasSubCode: false, code: { default: 'H19.1' } },
  '8562': { hasSubCode: false, code: { default: 'H19.2' } },
  '8611': { hasSubCode: false, code: { default: 'H22.1' } },
  '8612': { hasSubCode: false, code: { default: 'H22.2' } },
  '9512': { hasSubCode: false, code: { default: 'I17.1' } },
  '9901': { hasSubCode: false, code: { default: 'I15' } }
};
