import { supportedMunicipalities } from '@functions/config';
import { arrayOfValidFeature } from '@libs/schema-tools';
import { array, number, object, string } from 'yup';

/**
 * Schema for the update payload generated by calculateDelta
 */
const updatePayloadSchema = object({
  Created: arrayOfValidFeature('metadata.assetType').required(),
  Updated: arrayOfValidFeature('metadata.assetType').required(),
  Deleted: arrayOfValidFeature('metadata.assetType').required(),
  metadata: object({
    municipality: string().oneOf(supportedMunicipalities).required(),
    assetType: string().oneOf(['obstacles', 'trafficSigns']).required()
  }).required(),
  invalidInfrao: object({
    sum: number().required(),
    IDs: array().of(string()).required()
  }).required()
}).required();

export { updatePayloadSchema };
