import { supportedMunicipalities } from '@functions/config';
import { arrayOfMatchedFeature, arrayOfValidFeature } from '@libs/schema-tools';
import { array, number, object, string } from 'yup';
import { invalidFeatureSchema } from './geoJsonSchema';

/**
 * Schema for the update payload generated by calculateDelta
 */
const updatePayloadSchema = object({
  Created: arrayOfValidFeature('metadata.assetType').required(),
  Updated: arrayOfValidFeature('metadata.assetType').required(),
  Deleted: arrayOfValidFeature('metadata.assetType').required(),
  metadata: object({
    municipality: string().oneOf(supportedMunicipalities).required(),
    assetType: string().oneOf(['obstacles', 'trafficSigns']).required()
  }).required()
}).required();

const logsSchema = object({
  RejectedByLocation: object({
    sum: number().required(),
    rejected: array().default([]).of(invalidFeatureSchema).required()
  }),
  Accepted: object({
    Created: arrayOfMatchedFeature('metadata.assetType').required(),
    Updated: arrayOfMatchedFeature('metadata.assetType').required(),
    Deleted: arrayOfValidFeature('metadata.assetType', true).required()
  }),
  metadata: object({
    municipality: string().oneOf(supportedMunicipalities).required(),
    assetType: string().oneOf(['obstacles', 'trafficSigns']).required()
  }).required()
}).required();

export { updatePayloadSchema, logsSchema };
